name: flutter_example
description: A Flutter example for zxcvbnm
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_multiple_translations: ^1.0.1
  zxcvbnm: ^1.1.1
  zxcvbnm_flutter: ^1.1.1

dev_dependencies:
  intl_utils: any
  flutter_lints: any

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
